name: Selenium WebDriver Test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Chrome Driver
      run: |
        LATEST_CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -sS -L "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_mac64.zip" -o /tmp/chromedriver.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin

    - name: Build with Maven
      run: mvn -B clean package

    - name: Run Tests with TestNG
      run: mvn test
