name: Open Chrome Browser on Local Machine

on:
  workflow_dispatch:

jobs:
  open_chrome_browser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to Local Machine with SSH
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.0.14
        username: medelvecina
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          ssh-keyscan -t rsa 192.168.0.14 >> ~/.ssh/known_hosts
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no medelvecina@192.168.0.14 '
            cd /path/to/your/java/program
            export DISPLAY=:0
            mvn test -Dtest=OpenChromeBrowser
          '

    env:
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
