name: Open Chrome Browser on Local Machine

on:
  workflow_dispatch:

jobs:
  open_chrome_browser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.4.1
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Connect to Local Machine
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.0.14
        username: medelvecina
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /Users/medelvecina/Documents/eclipse-workspace/planit-tech-assessment-031223
          export DISPLAY=:0
          mvn test -Dtest=OpenChromeBrowser

secrets:
  SSH_PRIVATE_KEY:
    # Your private key
    # Base64-encoded string of the contents of the private key file
  SSH_KNOWN_HOSTS:
    # Your known_hosts file
    # Base64-encoded string of the contents of the known_hosts file
  SSH_PASSWORD:
    # Your SSH password
    # Encrypted secret created using the GitHub Actions secret feature
